### Aruco sensor processing

Experimentation for the development of an Aruco tag based sensor processing system. 

In [4]:
import sys
sys.path.append("..")
from settings import Config
import numpy as np
import cv2


In [5]:
from sensorprocessing.aruco.utils import  aruco_display

arucoDict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_5X5_100)
arucoParams = cv2.aruco.DetectorParameters()

In [7]:
camera_number = Config().values["robot"]["active_camera_list"][0]
print(camera_number)
#camera_number = 2
cap = cv2.VideoCapture(camera_number)

while(True):
    ret, frame = cap.read()
    if not ret:
        print("Capture frame returned False, exiting the loop")
        break
    frame = cv2.resize(frame, (640, 480))
    # imgresized = frame

    # insert ARUCO code here

    marker_corners, marker_ids, rejected_candidates = cv2.aruco.detectMarkers(
        frame, arucoDict, parameters=arucoParams)
    
    detected_markers = aruco_display(marker_corners, marker_ids, rejected_candidates, frame)

    # end of ARUCO code

    # cv2.imshow('Press q to exit', frame)
    cv2.imshow('Press q to exit', detected_markers)
    ret = cv2.waitKey(1)
    if ret != -1:
        ret2 = ret & 0xFF
        if ret2 == ord('q'):
            break
# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

2
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5
[Inference] ArUco marker ID: 5


In [16]:
print(marker_corners)

(array([[[587., 137.],
        [608., 136.],
        [608., 154.],
        [587., 155.]]], dtype=float32), array([[[531., 203.],
        [550., 203.],
        [550., 221.],
        [531., 221.]]], dtype=float32), array([[[533., 141.],
        [550., 139.],
        [550., 156.],
        [533., 158.]]], dtype=float32))


In [17]:
marker_ids

array([[2],
       [9],
       [1]], dtype=int32)

In [20]:
frame.shape

(480, 640, 3)

This code creates the encoding for the Aruco markers because 

In [ ]:
MARKER_COUNT = 10
XMAX = float(frame.shape[1])
YMAX = float(frame.shape[0])
NORMALIZER = np.tile([XMAX, YMAX], 4)

z = np.ones(MARKER_COUNT * (8 + 1)) * -1.0
for id, corners in zip(marker_ids, marker_corners):
    detection = corners[0].flatten() / NORMALIZER
    idn = id[0]
    z[idn * (8+1):(idn+1) * (8+1)-1] = detection


In [36]:
z[0:9]

array([-1., -1., -1., -1., -1., -1., -1., -1., -1.])